export interface LegacyCuisineRegion {
  id: string;
  cuisines: readonly string[];
}

export const LEGACY_CUISINE_REGIONS: readonly LegacyCuisineRegion[] = [
  {
    id: "mena",
    cuisines: [
      "Lebanese",
      "Palestinian",
      "Syrian",
      "Egyptian",
      "Moroccan",
      "Turkish",
      "Iraqi",
      "Jordanian",
      "Saudi",
      "Yemeni",
      "Emirati",
      "Tunisian",
      "Algerian",
      "Persian",
    ],
  },
  {
    id: "east_se_asia",
    cuisines: [
      "Japanese",
      "Chinese",
      "Korean",
      "Thai",
      "Vietnamese",
      "Filipino",
      "Indonesian",
      "Malaysian",
      "Singaporean",
      "Taiwanese",
      "Cambodian",
      "Burmese",
    ],
  },
  {
    id: "south_asia",
    cuisines: [
      "Indian",
      "Pakistani",
      "Sri Lankan",
      "Bangladeshi",
      "Nepali",
      "Afghan",
    ],
  },
  {
    id: "europe",
    cuisines: [
      "Italian",
      "French",
      "Spanish",
      "Greek",
      "Portuguese",
      "German",
      "British",
      "Polish",
      "Swedish",
      "Hungarian",
      "Dutch",
      "Swiss",
      "Austrian",
      "Belgian",
      "Russian",
      "Ukrainian",
      "Georgian",
    ],
  },
  {
    id: "americas",
    cuisines: [
      "American",
      "Mexican",
      "Brazilian",
      "Peruvian",
      "Argentine",
      "Colombian",
      "Cuban",
      "Jamaican",
      "Canadian",
      "Chilean",
      "Venezuelan",
      "Puerto Rican",
      "Salvadoran",
      "Haitian",
      "Trinidadian",
    ],
  },
  {
    id: "africa",
    cuisines: [
      "Ethiopian",
      "Nigerian",
      "South African",
      "Ghanaian",
      "Senegalese",
      "Kenyan",
      "Somali",
      "Tanzanian",
      "Sudanese",
    ],
  },
  {
    id: "oceania",
    cuisines: ["Australian", "New Zealand", "Hawaiian", "Polynesian"],
  },
];
